# Crea una calculadora ...
name: ejercicio 4

on:
  workflow_dispatch:
    inputs:
      operacion:
        description: 'Operacion (suma, resta, multiplicacion, division)'
        required: true
      valores:
        description: 'Valores de entrada separados por comas (ej.: 10,20,30)'
        required: true

jobs:
  calcular:
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        run: echo "Configurando la calculadora..."

      - name: Usar la acción compuesta de calculadora
        id: calculadora
        uses: ./actions/calculadora/calculate.sh
        with:
          operacion: "${{ github.event.inputs.operacion }}"
          valores: "${{ github.event.inputs.valores }}"

      - name: Obtener resultado
        run: |
          echo "El resultado es: ${{ steps.calculadora.outputs.resultado }}"