name: ejercicio 6

on:
  workflow_dispatch:

jobs:
  call-reusable-docker:
    uses: ./.github/workflows/ejercicio-6-reusable.yml
    with:
      image: python-api
      tag: ralonsostemdo/python-api:latest
    secrets:
      dh_user: ${{ secrets.DH_USER }}
      dh_password: ${{ secrets.DH_PASSWORD }}