# Login en azure
name: ejercicio 5
on:
  workflow_dispatch:
    
jobs:
    login-azure:
      runs-on: ubuntu-latest
      steps:

      - name: Login con action
        uses: azure/login@v2
        with:
          creds: "${{ secrets.AZURE_CREDENTIALS }}"
          allow-no-subscriptions: true
          enable-AzPSSession: true